### ISSUE TITLE
可以增加一个输出吗？

### ISSUE THREAD

**Issue by vinter-wu** [ningcol/haier-node#1]
我用这个节点可以控制家里热水器的开关，但是还想利用回复的语音内容调用call-service，做一个状态反馈。但是提示api失败了。不知道要怎么处理了。Call-service error. extra keys not allowed @ data['nlpTime']

**Comment by ningcol** [comment]
你输入指令后，你打印出他返回的信息，自己做截取，再调用其他服务就好了。你的意思是你输入指令返回错误了？

**Comment by ningcol** [comment]
> 你输入指令后，你打印出他返回的信息，自己做截取，再调用其他服务就好了。你的意思是你输入指令返回错误了？


你输入指令后，你打印出他返回的信息，自己做截取，再调用其他服务就好了。你的意思是你输入指令返回错误了？

**Comment by ningcol** [comment]
> 我用这个节点可以控制家里热水器的开关，但是还想利用回复的语音内容调用call-service，做一个状态反馈。但是提示api失败了。不知道要怎么处理了。Call-service error. extra keys not allowed @ data['nlpTime']


你输入指令后，你打印出他返回的信息，自己做截取，再调用其他服务就好了。你的意思是你输入指令返回错误了？
