### ISSUE TITLE
api错误

### ISSUE THREAD

**Issue by martinnly** [ningcol/haier-node#2]
节点今天突然显示错误
Error: Request Error
url: http://ai.haier.net:11000/access/ai-access/nlp?engine=uapp&needcontent=yes&opmode=remote&syncmode=yes&ttssplit=no
retInfo: undefined
code: undefined

**Comment by pcj1997** [comment]
同遇到这种情况，怀疑是海尔那边更新接口了，等大佬修复

**Comment by ningcol** [comment]
等我有时间看看

**Comment by pcj1997** [comment]
更新完目前报这个错，麻烦大佬看看，感谢！
（也尝试了删除海尔机器人的NR节点重新安装还是这样）
Error: Request Error
url: https://zj.haier.net/oauthserver/account/v1/login
retInfo: undefined
code: undefined

**Comment by ningcol** [comment]
> 更新完目前报这个错，麻烦大佬看看，感谢！ （也尝试了删除海尔机器人的NR节点重新安装还是这样） Error: Request Error url: https://zj.haier.net/oauthserver/account/v1/login retInfo: undefined code: undefined

是最新版本么

**Comment by pcj1997** [comment]
确定是最新版本1.0.1

**Comment by ningcol** [comment]
> 确定是最新版本1.0.1

但是我这边试了都是ok的

**Comment by pcj1997** [comment]
好的大佬，那我再排查一下我这边环境是不是有问题

**Comment by pcj1997** [comment]
重启了HA后，恢复正常了，之前更新完仅重启了NR。

**Comment by martinnly** [comment]
更新完，重启了nodered和ha，网络页重启了一下，还是返回一样的错误

**Comment by pcj1997** [comment]
你可以考虑删掉NR里面海尔机器人这个节点，然后重新安装。
另外我这边还发现，如果使用NR的海尔机器人节点，手机上海尔智家就会提示在一台iPhone SE（看大佬的代码里面写的手机型号也该就是这个）上登录，手机app就自动退出了。

**Comment by martinnly** [comment]
试过重装节点，没用，我看论坛里其他人也是这样

**Comment by pcj1997** [comment]
试试改下海尔账号的密码，然后重新配置下NR里面的密码

**Comment by pcj1997** [comment]
别试了，我这边又出问题了，还是上午那个报错。。。。
Error: Request Error
url: https://zj.haier.net/oauthserver/account/v1/login
retInfo: undefined
code: undefined

**Comment by otherbanana** [comment]
我这里刚刚试了一下，也是报错，昨晚更新到最新版本来可以的了，刚刚一看又不行了
Error: Request Error
url: http://ai.haier.net:11000/access/ai-access/nlp?engine=uapp&needcontent=yes&opmode=remote&syncmode=yes&ttssplit=no
retInfo: undefined
code: undefined

**Comment by martinnly** [comment]
解决了，把大佬的版本号改一下就可以了，现在用的是7.19.2

**Comment by nightjoyip** [comment]
> 解决了，把大佬的版本号改一下就可以了，现在用的是7.19.2

7.1.4改成7.19.2就可以了？

**Comment by nightjoyip** [comment]
> 解决了，把大佬的版本号改一下就可以了，现在用的是7.19.2

果然可以了，牛B

**Comment by otherbanana** [comment]
确实可以，请问一下，是怎么发现的啊哈哈哈

**Comment by ningcol** [comment]
改下版本就行了，最近应该是甲流了，这几天班都没上，到时候再更新
