### ISSUE TITLE
好像api又换了

### ISSUE THREAD

**Issue by otherbanana** [ningcol/haier-node#3]
目前更新到最新版，还是报错。然后自己抓包看了一下好像api换成了
https://zj.haier.net/api-gw/oauthserver/account/nvc/v2/login

**Comment by DreamXiaoHai** [comment]
@ningcol 大佬麻烦再看下，好像是api又换了

**Comment by DreamXiaoHai** [comment]
好像接了分控功能了，感觉无了啊

**Comment by chenjiezb** [comment]
Error: Request Error
url: http://ai.haier.net:11000/access/ai-access/nlp?engine=uapp&needcontent=yes&opmode=remote&syncmode=yes&ttssplit=no
retInfo: undefined
code: undefined

**Comment by ningcol** [comment]
你们改下版本号就行了，然后把不用的手机号添加个家庭成员，这样你们也可以用常用的号继续登录，不会被挤下来

**Comment by otherbanana** [comment]
> 好像接了分控功能了，感觉无了啊

已经解决了啊，看这里
[https://github.com/ningcol/haier-node/issues/2#issuecomment-1483962549](url)

**Comment by chenjiezb** [comment]
> 你们改下版本号就行了，然后把不用的手机号添加个家庭成员，这样你们也可以用常用的号继续登录，不会被挤下来

你好！已将将节点升级到1.0.1版本，NR重启，新版本节点启用。也用其他手机号注册了海尔智家，加入了家庭。但无论用哪个账号在nr里登录，都会报错：

> Error: Request Error url: http://ai.haier.net:11000/access/ai-access/nlp?engine=uapp&needcontent=yes&opmode=remote&syncmode=yes&ttssplit=no retInfo: undefined code: undefined

是否是我操作上哪里不对？

**Comment by DreamXiaoHai** [comment]
@otherbanana 不是吧，issue2确实解决了，就用了一天感觉api又换了吧，你的是正常的？
我现在报的错跟 chenjiezb一样；
Error: Request Error
url: http://ai.haier.net:11000/access/ai-access/nlp?engine=uapp&needcontent=yes&opmode=remote&syncmode=yes&ttssplit=no
retInfo: undefined
code: undefined

**Comment by Mrxxy** [comment]
1.0.1版本，报错
Error: Request Error
url: http://ai.haier.net:11000/access/ai-access/nlp?engine=uapp&needcontent=yes&opmode=remote&syncmode=yes&ttssplit=no
retInfo: undefined
code: undefined

**Comment by otherbanana** [comment]
> 

我的依然可以啊

**Comment by otherbanana** [comment]
@DreamXiaoHai 我的正常

**Comment by DreamXiaoHai** [comment]
我看了一下代码，发现我的const.js里面的APP_VER 字段是老的，改成7.19.2之后就正常了，不知道为啥升级没有把他改过来。

**Comment by chenjiezb** [comment]
> 我看了一下代码，发现我的const.js里面的APP_VER 字段是老的，改成7.19.2之后就正常了，不知道为啥升级没有把他改过来。

谢谢！看了你的回帖，终于弄明白了改版本号是这个意思。我的NR现在也正常了。

**Comment by pcj1997** [comment]
我这边今天晚上又出现之前的问题了，我看海尔智家的版本号也还是7.19.2呀，请问各位大佬有遇到吗？

**Comment by pcj1997** [comment]
把APP_VER里面的版本号改成7.19.1，第二行的USER_AGENT的版本号还是7.19.2，这样是可以用的

**Comment by chenjiezb** [comment]
登录验证没有问题，但访问reboot的URL报错：
Error: Request Error
url: http://ai.haier.net:11000/access/ai-access/nlp?engine=uapp&needcontent=yes&opmode=remote&syncmode=yes&ttssplit=no
retInfo: undefined
code: undefined
在浏览器上访问返回如下信息：
{"response":"给小优升个级，我就能更好的帮你啦","retCode":"I00001-00011","retInfo":"appId为空","sn":"20230415111710863000691096","success":false}

**Comment by pcj1997** [comment]
可以看看这个帖子下面的回复，目前看改版本号只能解决一时的问题，用一段时间还会出问题
https://bbs.hassbian.com/forum.php?mod=viewthread&tid=16180&extra=page%3D1&ordertype=1
