### ISSUE TITLE
燃气热水器无法控制

### ISSUE THREAD

**Issue by zhu-cucu** [ningcol/haier-node#6]
在v1.02版本中，我在使用燃气热水器控制命令时，反馈的response: "/ù燃热热水器好像不能控制了"，导致无法控制热水器，怀疑师命令中出现 燃气热水器的地方，变成 然热热水器导致无法控制

**Comment by otherbanana** [comment]
我直接报错了Error: Request Error
url: http://ai.haier.net:11000/access/ai-access/nlp?engine=uapp&needcontent=yes&opmode=remote&syncmode=yes&ttssplit=no
retInfo: undefined
code: undefined
