### ISSUE TITLE
突然报错

### ISSUE THREAD

**Issue by otherbanana** [ningcol/haier-node#7]
提示retInfo: "/ù小优没有查到相关信息，请检查设备联网状态，/ù稍后再试"
response: "/ù请先登录智家APP并绑定设备后，/ù再进行语音控制"
但是进入app用语言控制又是正常的

**Comment by Edaaaaa** [comment]
+1 我这边也是这样提示

**Comment by Edaaaaa** [comment]
感觉似乎是海尔的系统升级了

**Comment by otherbanana** [comment]
不清楚啊，看看大家都遇到了还是只是部分。

**Comment by ningcol** [comment]
应该是海尔那边改接口了，目前没有精力反编译APP了，可以尝试使用 https://github.com/banto6/haier 这个项目

**Comment by DreamXiaoHai** [comment]
感谢大佬奉献！

**Comment by otherbanana** [comment]
@ningcol 真的真的，谢谢大佬！
